export const GET_PORTFOLIOS = 'GET_PORTFOLIOS'
export const GET_PORTFOLIO = 'GET_PORTFOLIO'
export const GET_ONLINE_CODES = 'GET_ONLINE_CODES'
export const GET_MORE_PORTFOLIOS = 'GET_MORE_PORTFOLIOS'

export const SEND_EMAIL = 'SEND_EMAIL'

export const RESET_PORTFOLIOS = 'RESET_PORTFOLIOS'
